name: Generate Example Charts

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Create out folder
        shell: bash
        run: mkdir out

      - name: Generate charts
        shell: bash
        run: ./src/main.py examples/*.txt --save-chart

      - name: Deploy Documentation to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out